### ISSUE TITLE
Drupal 10.3.x support missing

### ISSUE THREAD

**Issue by wvdvegt** [Ambient-Impact/drupal-olivero-dark#1]
The info.yml prevents this repo from being used in the lastest 10.3.x updates.

**Comment by Ambient-Impact** [comment]
That's mostly out of caution since core doesn't currently guarantee compatibility with this theme as Olivero does not officially support sub-theming; if you want to test this on 10.3.x and open a pull request, I'd be happy to merge it. I'm just pretty busy with other things right now.

**Comment by Ambient-Impact** [comment]
Closing as part of #2 being merged. Thanks!
